import type { LPModel } from "./lp-schema";

export const SAMPLE_MODELS: LPModel[] = [
  {
    id: "tp1-production",
    name: "TP1 — Plan de production",
    description: "Maximiser le profit d'une usine fabriquant 2 produits sous contraintes de ressources.",
    tags: ["production", "2 variables", "max"],
    sense: "max",
    variables: [
      { name: "x1", type: "continuous", lb: 0, description: "Unités produit A" },
      { name: "x2", type: "continuous", lb: 0, description: "Unités produit B" },
    ],
    objective: { coefficients: { x1: 30, x2: 50 } },
    constraints: [
      { name: "Atelier 1", coefficients: { x1: 3, x2: 2 }, operator: "<=", rhs: 18 },
      { name: "Atelier 2", coefficients: { x1: 1, x2: 2 }, operator: "<=", rhs: 8 },
      { name: "Atelier 3", coefficients: { x2: 1 }, operator: "<=", rhs: 6 },
    ],
  },
  {
    id: "tp2-mix",
    name: "TP2 — Mix alimentaire",
    description: "Minimiser le coût d'un régime tout en respectant des apports nutritionnels.",
    tags: ["mix", "min", "nutrition"],
    sense: "min",
    variables: [
      { name: "p1", type: "continuous", lb: 0, description: "Quantité aliment 1" },
      { name: "p2", type: "continuous", lb: 0, description: "Quantité aliment 2" },
      { name: "p3", type: "continuous", lb: 0, description: "Quantité aliment 3" },
    ],
    objective: { coefficients: { p1: 4, p2: 6, p3: 5 } },
    constraints: [
      { name: "Protéines", coefficients: { p1: 3, p2: 2, p3: 4 }, operator: ">=", rhs: 12 },
      { name: "Glucides", coefficients: { p1: 2, p2: 5, p3: 1 }, operator: ">=", rhs: 10 },
      { name: "Lipides", coefficients: { p1: 1, p2: 1, p3: 2 }, operator: ">=", rhs: 6 },
    ],
  },
  {
    id: "tp3-investissement",
    name: "TP3 — Allocation d'investissement",
    description: "Répartir un capital sur 3 actifs pour maximiser le rendement attendu.",
    tags: ["finance", "max"],
    sense: "max",
    variables: [
      { name: "a", type: "continuous", lb: 0, description: "Actif A (8% rendement)" },
      { name: "b", type: "continuous", lb: 0, description: "Actif B (12% rendement)" },
      { name: "c", type: "continuous", lb: 0, description: "Actif C (6% rendement, sécurisé)" },
    ],
    objective: { coefficients: { a: 0.08, b: 0.12, c: 0.06 } },
    constraints: [
      { name: "Capital total", coefficients: { a: 1, b: 1, c: 1 }, operator: "<=", rhs: 100000 },
      { name: "Risque max", coefficients: { a: 0.2, b: 0.6, c: 0.1 }, operator: "<=", rhs: 30000 },
      { name: "Min sécurisé", coefficients: { c: 1 }, operator: ">=", rhs: 20000 },
    ],
  },
  {
    id: "tp4-transport",
    name: "TP4 — Problème de transport",
    description: "Minimiser le coût de transport entre 2 usines et 3 clients avec contraintes d'offre/demande.",
    tags: ["transport", "min", "réseau"],
    sense: "min",
    variables: [
      { name: "x11", type: "continuous", lb: 0, description: "Usine 1 → Client 1" },
      { name: "x12", type: "continuous", lb: 0, description: "Usine 1 → Client 2" },
      { name: "x13", type: "continuous", lb: 0, description: "Usine 1 → Client 3" },
      { name: "x21", type: "continuous", lb: 0, description: "Usine 2 → Client 1" },
      { name: "x22", type: "continuous", lb: 0, description: "Usine 2 → Client 2" },
      { name: "x23", type: "continuous", lb: 0, description: "Usine 2 → Client 3" },
    ],
    objective: { coefficients: { x11: 2, x12: 3, x13: 5, x21: 4, x22: 1, x23: 3 } },
    constraints: [
      { name: "Offre Usine 1", coefficients: { x11: 1, x12: 1, x13: 1 }, operator: "<=", rhs: 120 },
      { name: "Offre Usine 2", coefficients: { x21: 1, x22: 1, x23: 1 }, operator: "<=", rhs: 80 },
      { name: "Demande Client 1", coefficients: { x11: 1, x21: 1 }, operator: ">=", rhs: 60 },
      { name: "Demande Client 2", coefficients: { x12: 1, x22: 1 }, operator: ">=", rhs: 70 },
      { name: "Demande Client 3", coefficients: { x13: 1, x23: 1 }, operator: ">=", rhs: 50 },
    ],
  },
  {
    id: "tp5-affectation",
    name: "TP5 — Affectation de personnel",
    description: "Affecter 3 employés à 3 tâches pour minimiser le temps total d'exécution.",
    tags: ["affectation", "min", "entier"],
    sense: "min",
    variables: [
      { name: "y11", type: "binary", lb: 0, ub: 1, description: "Employé 1 → Tâche 1" },
      { name: "y12", type: "binary", lb: 0, ub: 1, description: "Employé 1 → Tâche 2" },
      { name: "y13", type: "binary", lb: 0, ub: 1, description: "Employé 1 → Tâche 3" },
      { name: "y21", type: "binary", lb: 0, ub: 1, description: "Employé 2 → Tâche 1" },
      { name: "y22", type: "binary", lb: 0, ub: 1, description: "Employé 2 → Tâche 2" },
      { name: "y23", type: "binary", lb: 0, ub: 1, description: "Employé 2 → Tâche 3" },
      { name: "y31", type: "binary", lb: 0, ub: 1, description: "Employé 3 → Tâche 1" },
      { name: "y32", type: "binary", lb: 0, ub: 1, description: "Employé 3 → Tâche 2" },
      { name: "y33", type: "binary", lb: 0, ub: 1, description: "Employé 3 → Tâche 3" },
    ],
    objective: { coefficients: { y11: 9, y12: 2, y13: 7, y21: 3, y22: 6, y23: 4, y31: 1, y32: 8, y33: 5 } },
    constraints: [
      { name: "Emp. 1 — une tâche", coefficients: { y11: 1, y12: 1, y13: 1 }, operator: "=", rhs: 1 },
      { name: "Emp. 2 — une tâche", coefficients: { y21: 1, y22: 1, y23: 1 }, operator: "=", rhs: 1 },
      { name: "Emp. 3 — une tâche", coefficients: { y31: 1, y32: 1, y33: 1 }, operator: "=", rhs: 1 },
      { name: "Tâche 1 — un emp.", coefficients: { y11: 1, y21: 1, y31: 1 }, operator: "=", rhs: 1 },
      { name: "Tâche 2 — un emp.", coefficients: { y12: 1, y22: 1, y32: 1 }, operator: "=", rhs: 1 },
      { name: "Tâche 3 — un emp.", coefficients: { y13: 1, y23: 1, y33: 1 }, operator: "=", rhs: 1 },
    ],
  },
  {
    id: "tp6-mélange",
    name: "TP6 — Mélange de carburant",
    description: "Minimiser le coût de production d'un carburant en mélangeant 3 composants sous contraintes de qualité.",
    tags: ["mélange", "min", "chimie"],
    sense: "min",
    variables: [
      { name: "c1", type: "continuous", lb: 0, description: "Composant 1 (2€/L)" },
      { name: "c2", type: "continuous", lb: 0, description: "Composant 2 (3€/L)" },
      { name: "c3", type: "continuous", lb: 0, description: "Composant 3 (1.5€/L)" },
    ],
    objective: { coefficients: { c1: 2, c2: 3, c3: 1.5 } },
    constraints: [
      { name: "Volume total", coefficients: { c1: 1, c2: 1, c3: 1 }, operator: "=", rhs: 1000 },
      { name: "Indice octane min", coefficients: { c1: 90, c2: 100, c3: 75 }, operator: ">=", rhs: 85000 },
      { name: "Soufre max", coefficients: { c1: 0.005, c2: 0.002, c3: 0.01 }, operator: "<=", rhs: 6 },
      { name: "Min C1", coefficients: { c1: 1 }, operator: ">=", rhs: 100 },
      { name: "Min C2", coefficients: { c2: 1 }, operator: ">=", rhs: 50 },
    ],
  },
];

export const getModelById = (id: string) => SAMPLE_MODELS.find((m) => m.id === id);
