/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultatsRouteImport } from './routes/resultats'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as EditeurRouteImport } from './routes/editeur'
import { Route as ComparateurRouteImport } from './routes/comparateur'
import { Route as BibliothequeRouteImport } from './routes/bibliotheque'
import { Route as IndexRouteImport } from './routes/index'

const ResultatsRoute = ResultatsRouteImport.update({
  id: '/resultats',
  path: '/resultats',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const EditeurRoute = EditeurRouteImport.update({
  id: '/editeur',
  path: '/editeur',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparateurRoute = ComparateurRouteImport.update({
  id: '/comparateur',
  path: '/comparateur',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliothequeRoute = BibliothequeRouteImport.update({
  id: '/bibliotheque',
  path: '/bibliotheque',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bibliotheque': typeof BibliothequeRoute
  '/comparateur': typeof ComparateurRoute
  '/editeur': typeof EditeurRoute
  '/parametres': typeof ParametresRoute
  '/resultats': typeof ResultatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bibliotheque': typeof BibliothequeRoute
  '/comparateur': typeof ComparateurRoute
  '/editeur': typeof EditeurRoute
  '/parametres': typeof ParametresRoute
  '/resultats': typeof ResultatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bibliotheque': typeof BibliothequeRoute
  '/comparateur': typeof ComparateurRoute
  '/editeur': typeof EditeurRoute
  '/parametres': typeof ParametresRoute
  '/resultats': typeof ResultatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bibliotheque'
    | '/comparateur'
    | '/editeur'
    | '/parametres'
    | '/resultats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bibliotheque'
    | '/comparateur'
    | '/editeur'
    | '/parametres'
    | '/resultats'
  id:
    | '__root__'
    | '/'
    | '/bibliotheque'
    | '/comparateur'
    | '/editeur'
    | '/parametres'
    | '/resultats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliothequeRoute: typeof BibliothequeRoute
  ComparateurRoute: typeof ComparateurRoute
  EditeurRoute: typeof EditeurRoute
  ParametresRoute: typeof ParametresRoute
  ResultatsRoute: typeof ResultatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultats': {
      id: '/resultats'
      path: '/resultats'
      fullPath: '/resultats'
      preLoaderRoute: typeof ResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editeur': {
      id: '/editeur'
      path: '/editeur'
      fullPath: '/editeur'
      preLoaderRoute: typeof EditeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparateur': {
      id: '/comparateur'
      path: '/comparateur'
      fullPath: '/comparateur'
      preLoaderRoute: typeof ComparateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bibliotheque': {
      id: '/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof BibliothequeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliothequeRoute: BibliothequeRoute,
  ComparateurRoute: ComparateurRoute,
  EditeurRoute: EditeurRoute,
  ParametresRoute: ParametresRoute,
  ResultatsRoute: ResultatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
